require('./tasks/styles')
require('./tasks/scripts')
require('./tasks/templates')
require('./tasks/images')
require('./tasks/fonts')
require('./tasks/favicons')
require('./tasks/start')
require('./tasks/build')
